#!/usr/bin/python3
# vim:se tw=0 sts=4 ts=4 et ai:
"""
evmk -- keyboard event data tool

Copyright © 2022 Osamu Aoki

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
USA
"""
# For main
import argparse
import logging

# deb: python3-systemd
from systemd import journal

# import locale
import sys

# from operator import itemgetter

# internal time unit is ms
import time
import struct

# select was not helpful
# import select
import collections

MIN_PYTHON = (3, 9)

if sys.version_info < MIN_PYTHON:
    sys.exit("Python {}.{} or later is required.\n".format(*MIN_PYTHON))

logger = logging.getLogger()
logger.addHandler(journal.JournalHandler())

#######################################################################
# common kbd event data constants and functions
#######################################################################
# * install "udevmon.service" in "/etc/systemd/system/"
# * run "sudo systemctl enamble udevmon.service"
# * install "keymap.csv" to "/etc/interception/"
# * install "evmk" to /usr/local/bin/"
# * install "laptop-kbd.yaml" into "/etc/interception/udevmon.d"
# * content of "laptop-kbd.yaml":
#  - JOB: "intercept -g $DEVNODE | /usr/local/bin/evmk -t -d -g -l INFO | uinput -d $DEVNODE"
#    -  LINK: /dev/input/by-path/platform-i8042-serio-0-event-kbd


TAP_HOLD_TIME = 200  # ms
TAP_GAP_TIME = 150  # ms
KC_ESC = 1
PASS_THROUGH_KC = KC_ESC
PASS_THROUGH_COUNT = 100
CONF_FILE = "/etc/interception/keymap.csv"


EV_TYPE = {
    0: "SYN",
    1: "KEY",
    2: "REL",
    3: "ABS",
    4: "MSC",
    5: "SW",
    17: "LED",
    18: "SND",
    19: "REP",
    20: "FF",
    21: "PWR",
    22: "FF_STATUS",
}

TYPE_SYN = 0
TYPE_KEY = 1
TYPE_MSC = 4
TYPE_LED = 17

SYN_CODE = {0: "REPORT", 1: "CONFIG", 2: "MT_REPORT", 3: "DROPPED"}

SYN_REPORT = 0

KEY_CODE = {
    0: "RESERVED",
    1: "ESC",
    2: "1",
    3: "2",
    4: "3",
    5: "4",
    6: "5",
    7: "6",
    8: "7",
    9: "8",
    10: "9",
    11: "0",
    12: "MINUS",
    13: "EQUAL",
    14: "BACKSPACE",
    15: "TAB",
    16: "Q",
    17: "W",
    18: "E",
    19: "R",
    20: "T",
    21: "Y",
    22: "U",
    23: "I",
    24: "O",
    25: "P",
    26: "LEFTBRACE",
    27: "RIGHTBRACE",
    28: "ENTER",
    29: "LEFTCTRL",
    30: "A",
    31: "S",
    32: "D",
    33: "F",
    34: "G",
    35: "H",
    36: "J",
    37: "K",
    38: "L",
    39: "SEMICOLON",
    40: "APOSTROPHE",
    41: "GRAVE",
    42: "LEFTSHIFT",
    43: "BACKSLASH",
    44: "Z",
    45: "X",
    46: "C",
    47: "V",
    48: "B",
    49: "N",
    50: "M",
    51: "COMMA",
    52: "DOT",
    53: "SLASH",
    54: "RIGHTSHIFT",
    55: "KPASTERISK",
    56: "LEFTALT",
    57: "SPACE",
    58: "CAPSLOCK",
    59: "F1",
    60: "F2",
    61: "F3",
    62: "F4",
    63: "F5",
    64: "F6",
    65: "F7",
    66: "F8",
    67: "F9",
    68: "F10",
    69: "NUMLOCK",
    70: "SCROLLLOCK",
    71: "KP7",
    72: "KP8",
    73: "KP9",
    74: "KPMINUS",
    75: "KP4",
    76: "KP5",
    77: "KP6",
    78: "KPPLUS",
    79: "KP1",
    80: "KP2",
    81: "KP3",
    82: "KP0",
    83: "KPDOT",
    # 84 skipped with reason
    85: "ZENKAKUHANKAKU",
    86: "102ND",
    87: "F11",
    88: "F12",
    89: "RO",
    90: "KATAKANA",
    91: "HIRAGANA",
    92: "HENKAN",
    93: "KATAKANAHIRAGANA",
    94: "MUHENKAN",
    95: "KPJPCOMMA",
    96: "KPENTER",
    97: "RIGHTCTRL",
    98: "KPSLASH",
    99: "SYSRQ",
    100: "RIGHTALT",
    101: "LINEFEED",
    102: "HOME",
    103: "UP",
    104: "PAGEUP",
    105: "LEFT",
    106: "RIGHT",
    107: "END",
    108: "DOWN",
    109: "PAGEDOWN",
    110: "INSERT",
    111: "DELETE",
    112: "MACRO",
    113: "MUTE",
    114: "VOLUMEDOWN",
    115: "VOLUMEUP",
    116: "POWER",
    117: "KPEQUAL",
    118: "KPPLUSMINUS",
    119: "PAUSE",
    120: "SCALE",
    121: "KPCOMMA",
    122: "HANGEUL",
    123: "HANJA",
    124: "YEN",
    125: "LEFTMETA",
    126: "RIGHTMETA",
    127: "COMPOSE",
    127: "COMPOSE",
    143: "WAKEUP",
}

KC_WAKEUP = 143  # safe default previous key

KC_LEFT_SHIFT = 42
KC_LEFT_CTRL = 29
KC_LEFT_ALT = 56
KC_LEFT_META = 125
KC_RIGHT_SHIFT = 54
KC_RIGHT_CTRL = 97
KC_RIGHT_ALT = 100
KC_RIGHT_META = 126

MODKEYS = [
    KC_LEFT_SHIFT,
    KC_LEFT_CTRL,
    KC_LEFT_ALT,
    KC_LEFT_META,
    KC_RIGHT_SHIFT,
    KC_RIGHT_CTRL,
    KC_RIGHT_ALT,
    KC_RIGHT_META,
]

MOD_LAYER0 = 0
MOD_LAYER1 = 1
MOD_LAYER2 = 2
MOD_LAYER3 = 3
MOD_LAYER4 = 4
MOD_LAYER5 = 5
MOD_LAYER6 = 6
MOD_LAYER7 = 7

KEY_UP = 0
KEY_DN = 1
KEY_RP = 2

KEY_VALS = {
    KEY_UP: ["↑", "UP", "RELEASE"],
    KEY_DN: ["↓", "DN", "PRESS"],
    KEY_RP: ["→", "RP", "REPEAT"],
}

MSC_CODE = {
    0: "SERIAL",
    1: "PULSELED",
    2: "GESTURE",
    3: "RAW",
    4: "SCAN",
    5: "TIMESTAMP",
}

MSC_SCAN = 4


def read_keymap(fn="keymap.csv"):
    with open(fn) as file:
        n = file.readline()
        if n != "KBD event table\n":
            logger.critical("Invalid keymap.csv data format.  Exit.")
            exit(1)
        n = file.readline().split(",")
        M = int(n[0], 0)  # 128
        N = int(n[1], 0)  # 3
        keymap = []
        for i in range(M):
            l = file.readline()
            n = l.split(",")
            keymap.append([])
            for j in range(N):
                keymap[i].append(int(n[j + 1], 0))
        return (M, N, keymap)


# In order to simplify print/log formatting, use -1 as None for positive
# integer event data
NONE = -1
# Dual function key flag
TBDKEY = -1  # -1: Need additional following key inputs to determine
BASEKEY = 0  #  0: Use low 16 bits (base code)
MODKEY = 1  #  1: Use as mod key / layer key
#  3: Use low 16 bits (tap) -- double tap (LATER)
#  4: Use low 16 bits (tap) for repeat -- double tap and hold (LATER)

DFK = {
    TBDKEY: "TBD",
    BASEKEY: "BASE",
    MODKEY: "MOD",
}


class key_event_grp:
    # Keyboard event class
    def __init__(self):
        self.ev_t_s = NONE  # the last data time (s)
        self.ev_t_us = NONE  # the last data time (us)
        self.ev_type = TYPE_KEY  # the last data type MSC, KEY, SYN, LED, ...
        self.ev_code = KC_WAKEUP  # the last key code (mapped to new value)
        self.ev_code_orig = KC_WAKEUP  # the last key code (unmodified original value)
        self.ev_value = NONE  # the last key state 0, 1, 2
        self.time_ms = NONE  # the last data time (us)
        self.grp = False  # event grouped or not
        self.grp_type = NONE  # grouped data type
        self.grp_code = KC_WAKEUP  # grouped key code
        self.grp_code_orig = NONE  # que1key.grp_code (before mapping)
        self.grp_value = NONE  # grouped key state 0, 1, 2
        self.grp_scan = NONE  # grouped scan code
        self.grp_ready = False
        self.grp_error = False
        self.grp_map = None
        self.grp_dfk = BASEKEY  # see above
        return

    def update(self, ev_t_s, ev_t_us, ev_type, ev_code, ev_value, args):
        self.ev_type = ev_type
        self.ev_code = ev_code
        self.ev_value = ev_value
        if args.group:
            if self.ev_t_s == NONE and self.ev_t_us == NONE:
                self.ev_t_s = ev_t_s
                self.ev_t_us = ev_t_us
                self.time_ms = int(self.ev_t_s * 1000 + self.ev_t_us / 1000)
            elif self.ev_t_s == ev_t_s and self.ev_t_us == ev_t_us:
                pass
            else:
                logger.warning(
                    "I: TYPE={:02x} CODE={:02x} VALUE={:02x}: skewed timing ev_t_us: old={}.{:09d} new={}.{:09d}".format(
                        ev_type, self.ev_t_s, self.ev_t_us, ev_t_s, ev_t_us
                    )
                )
            if ev_type == TYPE_MSC and ev_code == MSC_SCAN:
                self.grp_scan = ev_value
                self.grp_ready = False
            elif ev_type == TYPE_LED:
                self.grp_type = ev_type
                self.grp_code = ev_code
                self.grp_value = ev_value
                self.grp_ready = False
            elif ev_type == TYPE_KEY:  # KEY (key code and value report)
                self.grp_type = ev_type
                self.grp_code = ev_code
                self.grp_code_orig = ev_code
                self.grp_value = ev_value
                self.grp_ready = False
            elif ev_type == TYPE_SYN and ev_code == SYN_REPORT:
                if (
                    self.grp_type == TYPE_KEY
                    and ev_value == KEY_DN
                    and self.grp_scan == NONE
                ):  # KEY
                    self.grp = True
                    self.grp_ready = True
                elif (
                    self.grp_type == TYPE_KEY
                    and ev_value == KEY_UP
                    and self.grp_scan != NONE
                ):
                    self.grp = True
                    self.grp_ready = True
                elif self.grp_type == TYPE_LED:
                    self.grp = True
                    self.grp_ready = True
                else:  # NON STANDARD SYN
                    self.grp = False
                    self.grp_ready = True
                    self.grp_error = True
            else:  # NON STANDARD NON-SYN
                self.grp = False
                self.grp_ready = True
                self.grp_error = True
        else:  # No grouping
            self.ev_t_s = ev_t_s
            self.ev_t_us = ev_t_us
            self.grp = False
            self.grp_ready = True

    def del_time_ms(self, last_time_ms):
        return self.time_ms - last_time_ms

    def get_timestamp_string(self, last_time_ms, args):
        if args.timestamp:
            if args.delta:
                return "{:06d} ".format(self.del_time_ms(last_time_ms))
            else:
                return "{:016d} ".format(self.time_ms)
        else:
            return ""

    def get_grp_type_string(self):
        return "{:6s}".format(
            EV_TYPE.get(self.grp_type, "TYPE_{:02x}".format(self.grp_type))
        )

    def get_grp_code_string(self):
        return "{:10s} {:02x}".format(
            KEY_CODE.get(self.grp_code & 0x3FF, "*****"),
            self.grp_code,
        )

    def get_grp_code_orig_string(self):
        return "{:10s} {:02x}".format(
            KEY_CODE.get(self.grp_code_orig & 0x3FF, "*****"),
            self.grp_code_orig,
        )

    def get_grp_value_string(self, args):
        return KEY_VALS.get(self.grp_value, ["{:02x}".format(self.grp_value)] * 3)[
            args.key_value_string_type
        ]

    def get_grp_code_hex_string(self):
        return "{:02x}".format(self.grp_code)

    def get_grp_value_hex_string(self):
        return "{:02x}".format(self.grp_value)

    def get_grp_scan_string(self):
        return "{:02x}".format(self.grp_scan)

    def get_ev_type_string(self):
        return EV_TYPE.get(self.ev_type, "TYPE_{:02x}".format(self.ev_type))

    def get_msc_code_string(self):
        return MSC_CODE.get(self.ev_code, "MSC_x{:02x}".format(self.ev_code))

    def get_msc_value_string(self):
        return "{:02x}".format(self.ev_value)

    def get_key_code_string(self):
        return "{:10s} {:02x}".format(
            KEY_CODE.get(self.ev_code & 0x3FF, "*****"), self.ev_code
        )

    def get_key_value_string(self, args):
        return KEY_VALS.get(self.ev_value, ["{:02x}".format(self.ev_value)] * 3)[
            args.key_value_string_type
        ]

    def get_syn_code_string(self):
        return SYN_CODE.get(self.ev_code, "SYN_{:02x}".format(self.ev__code))

    def get_syn_value_string(self):
        return "{:02x}".format(self.ev_value)

    def get_ev_code_string(self):
        return "{:02x}".format(self.ev_code)

    def get_ev_value_string(self):
        return "{:02x}".format(self.ev_value)

    def get_dfk_string(self):
        return DFK.get(self.grp_dfk, "DFK_{:02x}".format(self.grp_dfk))

    def report_grp_error(self, id):
        # single ev data with some data for grp
        logger.warning(
            "{}: unexpected ev type={:02x} code={:02x} value={:02x} for group type={:02x} code={:02x} value={:02x} scan={:02x}".format(
                id,
                self.ev_type,
                self.ev_code,
                self.ev_value,
                self.grp_type,
                self.grp_code,
                self.grp_value,
                self.grp_scan,
            )
        )

    def report_layer(self, id, last_time_ms, layer, args):
        logger.info(
            "{}: {}layer={} {} -> {} {} dfk={}".format(
                id,
                self.get_timestamp_string(last_time_ms, args),
                layer,
                self.get_grp_code_orig_string(),
                self.get_grp_code_string(),
                self.get_grp_value_string(args),
                self.get_dfk_string(),
            )
        )

    def report_grp3_ev(self, id, last_time_ms, args):
        if self.grp_type == TYPE_KEY:
            logger.info(
                "{}: {}{} grp3 {} {} scan={} dfk={}".format(
                    id,
                    self.get_timestamp_string(last_time_ms, args),
                    self.get_grp_type_string(),
                    self.get_grp_code_string(),
                    self.get_grp_value_string(args),
                    self.get_grp_scan_string(),
                    self.get_dfk_string(),
                )
            )
        else:
            logger.info(
                "{}: {}{} grp3_no_key code={} value={} scan={} dfk={}".format(
                    id,
                    self.get_timestamp_string(last_time_ms, args),
                    self.get_grp_type_string(),
                    self.get_grp_code_hex_string(),
                    self.get_grp_value_hex_string(),
                    self.get_grp_scan_string(),
                    self.get_dfk_string(),
                )
            )

    def report_grp2_ev(self, id, last_time_ms, args):
        if self.grp_type == TYPE_KEY:
            logger.info(
                "{}: {}{} grp2 {} {} dfk={}".format(
                    id,
                    self.get_timestamp_string(last_time_ms, args),
                    self.get_grp_type_string(),
                    self.get_grp_code_string(),
                    self.get_grp_value_string(args),
                    self.get_dfk_string(),
                )
            )
        else:
            logger.info(
                "{}: {}{} grp2_no_key code={} value={} dfk={}".format(
                    id,
                    self.get_timestamp_string(last_time_ms, args),
                    self.get_grp_type_string(),
                    self.get_grp_code_hex_string(),
                    self.get_grp_value_hex_string(),
                    self.get_dfk_string(),
                )
            )

    def report_single_ev(self, id, last_time_ms, args):
        if self.ev_type == TYPE_MSC:
            logger.info(
                "{}: {}{} single {} {}".format(
                    id,
                    self.get_timestamp_string(last_time_ms, args),
                    self.get_ev_type_string(),
                    self.get_msc_code_string(),
                    self.get_msc_value_string(),
                )
            )
        elif self.ev_type == TYPE_KEY:
            logger.info(
                "{}: {}{} single {} {}".format(
                    id,
                    self.get_timestamp_string(last_time_ms, args),
                    self.get_ev_type_string(),
                    self.get_key_code_string(),
                    self.get_key_value_string(args),
                )
            )
        elif self.ev_type == TYPE_SYN:
            logger.info(
                "{}: {}{} single {} {}".format(
                    id,
                    self.get_timestamp_string(last_time_ms, args),
                    self.get_ev_type_string(),
                    self.get_syn_code_string(),
                    self.get_syn_value_string(),
                )
            )
        else:  # others
            logger.info(
                "{}: {}{} single ev_code={} ev_value={}".format(
                    id,
                    self.get_timestamp_string(last_time_ms, args),
                    self.get_ev_type_string(),
                    self.get_ev_code_string(),
                    self.get_ev_value_string(),
                )
            )

    def report_ev(self, id, last_time_ms, args):
        if self.grp and self.grp_scan != NONE:
            self.report_grp3_ev(id, last_time_ms, args)
        elif self.grp:  #  key.grp_scan is NONE:
            self.report_grp2_ev(id, last_time_ms, args)
        else:  # key.grp==False
            if self.grp_error:
                self.report_grp_error(id)
            self.report_single_ev("I", last_time_ms, args)


def report_que(que, id, last_time_ms, layer, args):
    for i in range(len(que)):
        quekey = que[i]
        idx = "{} {}/{} {}".format(id, i, len(que), layer)
        quekey.report_ev(idx, last_time_ms, args)


class Dfk_State:
    def __init__(self):
        self.last_code = KC_WAKEUP
        self.last_dfk = BASEKEY


class Input_State:
    def __init__(self, last_time_ms, layer, pass_through):
        self.last_code_orig = KC_WAKEUP
        self.last_time_ms = last_time_ms
        self.layer = layer
        self.pass_through = pass_through


class Output_State:
    def __init__(self, last_time_ms):
        self.last_time_ms = last_time_ms

    #################################################################
    # KEY no conversion for grp
    #################################################################


def pass_through_input_que(que1, que2):
    key = que1.popleft()
    key.grp_dfk = BASEKEY
    key.grp_code = key.grp_code_orig
    que2.append(key)

    #################################################################
    # KEY conversion for grp with input_state.layer
    #################################################################


def process_input_que(que1, que2, M, N, dfk_state, input_state, args):
    #################################################################
    # KEY conversion for grp with input_state.layer
    #################################################################
    key = que1[0]
    if key.grp and key.grp_type == TYPE_KEY and key.grp_code_orig < M:
        key.grp_code = key.grp_map[input_state.layer]
        if key.grp_value == KEY_DN:
            if key.grp_code & 0xFFFF000 == 0:
                key.grp_dfk = BASEKEY
            elif (
                key.del_time_ms(input_state.last_time_ms) < TAP_GAP_TIME
                and input_state.last_code_orig == key.grp_code_orig
            ):
                key.grp_dfk = BASEKEY
            else:
                key.grp_dfk = TBDKEY
                # let's check followings inputs
                tapped_keys = {}
                for i in range(1, len(que1), 1):
                    if que1[i].del_time_ms(key.time_ms) < TAP_HOLD_TIME:
                        if (
                            que1[i].grp_value == KEY_DN
                            and que1[i].grp_code_orig != key.grp_code_orig
                        ):
                            tapped_keys[i] = que1[i].grp_code_orig
                        if (
                            que1[i].grp_value != KEY_DN
                            and que1[i].grp_code_orig != key.grp_code_orig
                            and que1[i].grp_code_orig in tapped_keys.values()
                        ):
                            # other KEY tapped or held dn/up
                            key.grp_dfk = MODKEY
                            for j in range(1, len(que1)):
                                if que1[j].grp_code_orig == key.grp_code_orig:
                                    que1[j].grp_dfk = MODKEY
                                    if que1[j].grp_value == KEY_UP:
                                        break
                            if "3" in args.section.upper():
                                key.report_ev(
                                    "P3 MOD(external)",
                                    input_state.last_time_ms,
                                    args,
                                )
                        if (
                            que1[i].grp_value == KEY_UP
                            and que1[i].grp_code_orig == key.grp_code_orig
                        ):
                            for j in range(i + 1):
                                if que1[j].grp_code_orig == key.grp_code_orig:
                                    que1[j].grp_dfk = BASEKEY
                            if "3" in args.section.upper():
                                key.report_ev(
                                    "P3 TAP(time)", input_state.last_time_ms, args
                                )
                            break
                    else:
                        key.grp_dfk = MODKEY
                        for j in range(1, len(que1)):
                            if que1[j].grp_code_orig == key.grp_code_orig:
                                que1[j].grp_dfk = MODKEY
                                if que1[j].grp_value == KEY_UP:
                                    break
                        if "3" in args.section.upper():
                            key.report_ev(
                                "P3 MOD(time)", input_state.last_time_ms, args
                            )
                        break
            dfk_state[key.grp_code_orig].last_dfk = key.grp_dfk
            dfk_state[key.grp_code_orig].last_code = key.grp_code
        elif key.grp_value == KEY_UP:
            key.grp_dfk = dfk_state[key.grp_code_orig].last_dfk
            key.grp_code = dfk_state[key.grp_code_orig].last_code
            if key.grp_dfk == BASEKEY:
                input_state.last_time_ms = key.time_ms
                input_state.last_code_orig = key.grp_code_orig
        else:  # elif key.grp_value == KEY_RP:
            key.grp_dfk = dfk_state[key.grp_code_orig].last_dfk
            key.grp_code = dfk_state[key.grp_code_orig].last_code
        if "3" in args.section.upper():
            key.report_layer("P3", input_state.last_time_ms, input_state.layer, args)

        #############################################################
        # Report que1 after KEY_DN processing
        #############################################################
        if "4" in args.section.upper():
            report_que(que1, "P4", input_state.last_time_ms, input_state.layer, args)
    #################################################################
    # Pass from key to que2
    #################################################################
    if "5" in args.section.upper():
        key.report_ev("P5", input_state.last_time_ms, args)
    if key.grp and key.grp_type == TYPE_KEY and key.grp_code_orig < M:
        if key.grp_dfk == BASEKEY:
            # logger.info("BASE: len={} code={:02x} layer= {} dfk={}".format(len(que1), key.grp_code, input_state.layer, key.grp_dfk))
            que1.popleft()
            if key.grp_value == KEY_RP:
                if key.grp_code not in MODKEYS:
                    que2.append(key)
            else:  # key.grp_value == KEY_UP or KEY_DN
                que2.append(key)
        elif key.grp_dfk == MODKEY:  # only .grp=True
            que1.popleft()
            mod = key.grp_code >> 16
            # modifiers (mod low bits) are not mutually exclusive
            if mod & (1 << 0):
                key.grp_code = KC_LEFT_SHIFT
                if key.grp_value != KEY_RP:
                    que2.append(key)
            if mod & (1 << 1):
                key.grp_code = KC_LEFT_CTRL
                if key.grp_value != KEY_RP:
                    que2.append(key)
            if mod & (1 << 2):
                key.grp_code = KC_LEFT_ALT
                if key.grp_value != KEY_RP:
                    que2.append(key)
            if mod & (1 << 3):
                key.grp_code = KC_LEFT_META
                if key.grp_value != KEY_RP:
                    que2.append(key)
            if mod & (1 << 4):
                key.grp_code = KC_RIGHT_SHIFT
                if key.grp_value != KEY_RP:
                    que2.append(key)
            if mod & (1 << 5):
                key.grp_code = KC_RIGHT_CTRL
                if key.grp_value != KEY_RP:
                    que2.append(key)
            if mod & (1 << 6):
                key.grp_code = KC_RIGHT_ALT
                if key.grp_value != KEY_RP:
                    que2.append(key)
            if mod & (1 << 7):
                key.grp_code = KC_RIGHT_META
                if key.grp_value != KEY_RP:
                    que2.append(key)
            # layers (mod low bits) are mutually exclusive
            if mod & 0xFF00:  # layer
                if key.grp_value == KEY_UP:  # Released
                    input_state.layer = MOD_LAYER0
                else:
                    # elif key.grp_value == KEY_DN:  # Pressed
                    if mod & (1 << 8):
                        input_state.layer = MOD_LAYER0
                    elif mod & (1 << 9):
                        input_state.layer = MOD_LAYER1
                    elif mod & (1 << 10):
                        input_state.layer = MOD_LAYER2
                    elif mod & (1 << 11):
                        input_state.layer = MOD_LAYER3
                    elif mod & (1 << 12):
                        input_state.layer = MOD_LAYER4
                    elif mod & (1 << 13):
                        input_state.layer = MOD_LAYER5
                    elif mod & (1 << 14):
                        input_state.layer = MOD_LAYER6
                    elif mod & (1 << 15):
                        input_state.layer = MOD_LAYER7
                    else:
                        pass
                    if input_state.layer >= N:
                        input_state.layer = N - 1  # force override
                    # logger.info("M: layer changed to {}".format(input_state.layer))
                # else:  # Repeat
                #    pass  # NOP
        else:  # key.grp_dfk == TBDPKEY
            # no que1.popleft()
            # len(que1) is not 0, force to exit look with break required
            return True
    else:  # single, LED, high-bit (WAKEUP)
        que1.popleft()
        que2.append(key)
    # len(que1) should be 0
    return False


def process_output_que(que2, output_state, args):
    #####################################################################
    # outut que2
    #####################################################################
    while len(que2) != 0:
        key = que2.popleft()
        if "9" in args.section.upper():
            key.report_ev(">OUTPUT>", output_state.last_time_ms, args)
        if key.grp:
            if key.grp_scan != NONE:
                if not args.monitor:
                    sys.stdout.buffer.write(
                        EV.pack(key.ev_t_s, key.ev_t_us, 0, 0, key.grp_scan)
                    )
                    sys.stdout.buffer.write(
                        EV.pack(
                            key.ev_t_s,
                            key.ev_t_us,
                            1,
                            key.grp_code & 0x3FF,
                            key.grp_value,
                        )
                    )
                    sys.stdout.buffer.write(EV.pack(key.ev_t_s, key.ev_t_us, 4, 4, 0))
            else:
                if not args.monitor:
                    sys.stdout.buffer.write(
                        EV.pack(
                            key.ev_t_s,
                            key.ev_t_us,
                            1,
                            key.grp_code & 0x3FF,
                            key.grp_value,
                        )
                    )
                    sys.stdout.buffer.write(EV.pack(key.ev_t_s, key.ev_t_us, 4, 4, 1))
        else:  # single
            if not args.monitor:
                sys.stdout.buffer.write(
                    EV.pack(
                        key.ev_t_s,
                        key.ev_t_us,
                        key.ev_type,
                        key.ev_code,
                        key.ev_value,
                    )
                )
        output_state.last_time_ms = key.time_ms
        # Seemingly good idea of flush() causes infinite repeat-key problem
        # sys.stdout.buffer.flush()


#######################################################################
# sub-commands
#######################################################################

EV = struct.Struct("llHHI")
# read event data from stdin and output to stdout
def read_and_write(args):
    que1 = collections.deque()
    que2 = collections.deque()
    (M, N, keymap) = read_keymap(fn=CONF_FILE)
    count = 0
    layer = 0
    key = key_event_grp()
    # initial dfk_state
    dfk_state = []
    for i in range(M):
        dfk_state.append(Dfk_State())
    # time_ms in ms (real) -- TAP_HOLD_TIME/2 ms offset
    time_ms = int(time.time_ns() / 1000000 - TAP_HOLD_TIME)
    # initial last_key_state_data
    input_state = Input_State(time_ms, layer, args.pass_through)
    output_state = Output_State(time_ms)
    while True:
        # use of select.select didn't work well
        #     timeout = 0.2  # timeout 200 ms later
        #     rlist, _, _ = select.select([sys.stdin], [], [], timeout)
        #     if rlist:  -- this doesn't read released key event
        #
        #####################################################################
        # read event data from stdin to que1
        #####################################################################
        data = sys.stdin.buffer.read(EV.size)
        (ev_t_s, ev_t_us, ev_type, ev_code, ev_value) = EV.unpack(data)
        # The following sets .grp_ready until SYN for grouped processing
        key.update(ev_t_s, ev_t_us, ev_type, ev_code, ev_value, args)
        # make a event group for each meaningful key move
        #   .grp_code=<key code>, .grp_value=<key state>, .grp_scan=<scan code>
        if not key.grp_ready:
            #  group data until SYN w/o calling key = key_event_grp()
            continue
        if (
            key.grp
            and key.grp_type == TYPE_KEY
            and key.grp_code_orig == PASS_THROUGH_KC
        ):
            count += 1
            if count > 1:
                logger.warning("count = {}".format(count))
        else:
            count = 0
        if count > PASS_THROUGH_COUNT:
            count = PASS_THROUGH_COUNT
            input_state.pass_through = True
            logger.warning("pass through enabled")
        #####################################################################
        # process group to set up initial internal values
        #####################################################################
        if key.grp and key.grp_type == TYPE_KEY and key.grp_code_orig < M:
            # mappable range KEY
            key.grp_map = keymap[key.grp_code_orig]
        #####################################################################
        # report input event
        #####################################################################
        if "1" in args.section.upper():
            key.report_ev("P1", input_state.last_time_ms, args)
        #####################################################################
        # update que1 data with the new input event
        #####################################################################
        que1.append(key)
        #####################################################################
        # monitor que1 data to be processed
        #####################################################################
        if "2" in args.section.upper():
            report_que(que1, "P2", input_state.last_time_ms, input_state.layer, args)
        #####################################################################
        # process que1 for key conversion with input_state.layer
        #####################################################################
        if input_state.pass_through:
            while len(que1) > 0:
                pass_through_input_que(que1, que2)
        else:
            while len(que1) > 0:
                if process_input_que(que1, que2, M, N, dfk_state, input_state, args):
                    break
        process_output_que(que2, output_state, args)
        del key
        key = key_event_grp()
    # LOOPEND


#######################################################################
# main: parse commandline parser
#######################################################################
def main():
    parser = argparse.ArgumentParser(
        description="""\
A collection of python scripts to play with evdev events.

version: {}

copyright 2022 Osamu Aoki <osamu@debian.org>

license: GPL 2.0+

See See https://github.com/osamuaoki/{}
""".format(
            "0.1", "evmk"
        ),
    )
    parser.add_argument(
        "-t",
        "--timestamp",
        action="store_true",
        default=False,
        help="with timestamp",
    )
    parser.add_argument(
        "-d",
        "--delta",
        action="store_true",
        default=False,
        help="time as delta",
    )
    parser.add_argument(
        "-v",
        "--value",
        action="store",
        default="utf-8",
        metavar="[u|a|o]",
        help="key state value for log (default=u for ↑ ↓ →)",
    )
    parser.add_argument(
        "-g",
        "--group",
        action="store_true",
        default=False,
        help="group by event grp ending with SYN",
    )
    parser.add_argument(
        "-m",
        "--monitor",
        action="store_true",
        default=False,
        help="monitor only (no stdout)",
    )
    parser.add_argument(
        "-p",
        "--pass-through",
        action="store_true",
        default=False,
        help="force pass through for input que",
    )
    parser.add_argument(
        "-s",
        "--section",
        action="store",
        default="9",
        help="section to activate log: [1|2|3|4|5|9] (1: input, 3: conversion, 9: output)",
    )
    parser.add_argument(
        "-l",
        "--log",
        action="store",
        default="WARNING",
        help="set logging level (default=WARNING)",
    )
    args = parser.parse_args()
    #######################################################################
    # Update variables with sanitization
    #######################################################################
    if args.log == "":
        logger.setLevel(logging.INFO)
    elif args.log[0].upper() == "D":
        logger.setLevel(logging.DEBUG)
    elif args.log[0].upper() == "I":
        logger.setLevel(logging.INFO)
    elif args.log[0].upper() == "W":
        logger.setLevel(logging.WARNING)
    elif args.log[0].upper() == "E":
        logger.setLevel(logging.ERROR)
    else:
        logger.setLevel(logging.CRITICAL)
    args = parser.parse_args()
    if args.value.upper()[0] == "U":  # UTF-8
        args.key_value_string_type = 0
    elif args.value.upper()[0] == "A":  # Single ASCII
        args.key_value_string_type = 1
    else:
        args.key_value_string_type = 2
    read_and_write(args)


#######################################################################
# Test code
#######################################################################
if __name__ == "__main__":
    main()
