#!/bin/sh -ex
# vim:se tw=0 sts=2 ts=2 et ai si:
DEVNODE="/dev/input/by-path/platform-i8042-serio-0-event-kbd"
#DEVNODE="/dev/input/by-id/usb-osamuaoki_cgc56-if01-event-kbd"
sudo intercept "$DEVNODE" | \
  python3 ./evmk -t -d -s imo --log=INFO >/dev/null 
